- name: Create instance 1
  hosts: localhost
  gather_facts: false
  roles:
    - create_vm

- name: Create instance 2
  hosts: localhost
  gather_facts: false
  roles:
    - role: create_vm
      vars:
        disk_name: kira-disk-instance-2
        address_name: kira-address-instance-2
        instance_name: kiratech-instance-2
        swarm_group_name: docker_swarm_worker

- name: Check partition space
  hosts: gcp_instances
  become: true
  roles:
    - check_partition

- name: Install docker and docker-compose
  hosts: gcp_instances
  become: true
  roles:
    - role: geerlingguy.docker
      # vars:
        # docker_daemon_options:
          # tls: false
          # hosts: ["tcp://0.0.0.0:2376"]

- name: Secure docker api
  hosts: gcp_instances
  become: true
  roles:
    - role: secure_docker_api

- name: Set up a Docker Swarm on VMs
  hosts: gcp_instances
  become: true
  roles:
    - role: atosatto.docker-swarm
      vars:
        skip_docker_py: true
        skip_docker_compose: true
