- name: Create instance 1
  hosts: localhost
  gather_facts: false
  roles: 
    - create-vm

- name: Create instance 2
  hosts: localhost
  gather_facts: false
  roles: 
    - role: create-vm
      vars:
        disk_name: kira-disk-instance-2
        address_name: kira-address-instance-2
        instance_name: kiratech-instance-2
        swarm_group_name: docker_swarm_worker

## TODO: complete
- name: check partition disk space
  hosts: gcp_instances
  tags:
         - check-partition 
  tasks:
    - community.general.parted: device=/dev/sda2 unit=MiB
      become: true
      register: sda2_info
    - name: Print sda2_info
      debug:
        var: sda2_info

- name: Install docker and docker-compose
  hosts: gcp_instances
  become: true
  roles:
    - role: geerlingguy.docker
      #vars:
        #docker_daemon_options:
          #tls: false
          #hosts: ["tcp://0.0.0.0:2376"]

- name: Copy certificates on docker server
  hosts: gcp_instances
  become: true
  tasks:
    - copy:
        src: docker-cert/
        dest: /etc/docker/
        owner: root
        mode: 0644
       

- name: Systemd patch.
  hosts: gcp_instances
  become: true
  tasks:
    - file:
        path: /etc/systemd/system/docker.service.d
        owner: root
        group: root
        mode: 0755
        state: directory
    - copy:
        src: systemd-override.conf
        dest: /etc/systemd/system/docker.service.d/override.conf
        owner: root
        group: root
        mode: 0644
    - name: restart daemon and docker
      systemd:
        daemon_reload: true
        name: docker
        state: restarted   

- name: Set up a Docker Swarm on VMs
  hosts: gcp_instances
  become: true
  roles:
    - role: atosatto.docker-swarm
      vars:
        skip_docker_py: true
        skip_docker_compose: true