- name: Create instance 1
  hosts: localhost
  gather_facts: false
  roles: 
    - create-vm

- name: Create instance 2
  hosts: localhost
  gather_facts: false
  roles:
    - role: create-vm
      vars:
        disk_name: kira-disk-instance-2
        address_name: kira-address-instance-2
        instance_name: kiratech-instance-2
        swarm_group_name: docker_swarm_worker

## TODO: complete
- name: check partition disk space
  hosts: gcp_instances
  tags:
     - check-partition
  tasks:
    - name: Get device info
      community.general.parted: device=/dev/sda2 unit=MiB
      become: true
      register: sda2_info
    - name: Print sda2_info
      debug:
        var: sda2_info

- name: Install docker and docker-compose
  hosts: gcp_instances
  become: true
  roles:
    - role: geerlingguy.docker
      # vars:
        # docker_daemon_options:
          # tls: false
          # hosts: ["tcp://0.0.0.0:2376"]

- name: Secure docker api
  hosts: gcp_instances
  become: true
  roles:
    - role: secure-docker-api

- name: Set up a Docker Swarm on VMs
  hosts: gcp_instances
  become: true
  roles:
    - role: atosatto.docker-swarm
      vars:
        skip_docker_py: true
        skip_docker_compose: true