- name: Copy certificates on docker server
  ansible.builtin.copy:
    src: docker-cert/
    dest: /etc/docker/
    owner: root
    mode: 0644

- name: Customize systemd
  block:
    - name: change systemd dir permission
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: override systemd config
      ansible.builtin.copy:
        src: systemd-override.conf
        dest: /etc/systemd/system/docker.service.d/override.conf
        owner: root
        group: root
        mode: 0644
    - name: restart daemon
      ansible.builtin.systemd:
        daemon_reload: true
        name: docker
        state: restarted
